language: android
jdk: oraclejdk8

env:
  global:
    - ANDROID_API_LEVEL=32
    - ANDROID_BUILD_TOOLS_VERSION=32.0.0

branches:
  only:
    - master

android:
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

  components:
    - tools
    - platform-tools

    # Version used in project
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION

    # SDK used to compile project
    - android-$ANDROID_API_LEVEL

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-$ANDROID_API_LEVEL

    # System Image (for emulation)
    - sys-img-armeabi-v7a-google_apis-$ANDROID_API_LEVEL

before_install:
  - chmod +x gradlew
  - chmod +x gradle/wrapper/gradle-wrapper.jar

  # Get past license bug
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"

script:
  - ./gradlew build jacocoTestReport assembleAndroidTest

after_success:
  - bash <(curl -s https://codecov.io/bash)

