buildscript {
    ext {
        ver_sdk_min = 26
        ver_sdk = 34
        ver_buildtools = ver_sdk + ".0.0"
        ver_java = JavaVersion.VERSION_11
    }

    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.9.1'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.8.0"
        classpath "org.jacoco:org.jacoco.core:0.8.8"
    }
}

ext {
    buildToolsVersion = ver_buildtools
    compileSdkVersion = ver_sdk
    sourceCompatibility = ver_java
    targetCompatibility = ver_java
    defaultTargetSdkVersion = ver_sdk
    defaultMinSdkVersion = ver_sdk_min
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}
