---
version: 2.1
orbs:
  android: circleci/android@2.3.0
  codecov: codecov/codecov@3.2.5

workflows:
  app:
    jobs:
    - build

jobs:
  build:
    docker:
    - image: cimg/android:2023.07
    steps:
    - checkout
    - run: ./gradlew build
    - run: ./gradlew lint test
    - run: ./gradlew createDebugCoverageReport
    - codecov/upload
...
